InnAuthor/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views

from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace="users")),
    path('', include('startpage.urls', namespace="startpage")),
    path('news/', include('indexglav.urls', namespace="indexglav")),
    path('projects/', include('projects.urls', namespace="projects")),
    path('about/', include('about.urls', namespace="about")),
    path('exite/', include('exite.urls', namespace="exite")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('comments/', include('comments.urls', namespace="comments")),
    
    # Password reset URLs
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), 
        name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), 
        name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), 
        name='password_reset_complete'),
]

# Добавляем поддержку статических файлов в режиме отладки
urlpatterns += staticfiles_urlpatterns()

# Добавляем обработку медиа файлов в режиме отладки
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

about/urls.py
from django.urls import path
from . import views

app_name = "about"
urlpatterns = [
    path('', views.about, name='about'),
    path('liderplatform1/', views.liderplatform1, name='liderplatform1'),
    path('workshop1/', views.workshop1, name='workshop1'),
    path('documents1/', views.documents1, name='documents1'),
    path('shop1/', views.shop1, name='shop1'),
    path('service1/', views.service1, name='service1'),
    path('contact1/', views.contact1, name='contact1'),
]

indexglav/urls.py
from django.urls import path
from . import views

app_name = "indexglav"
urlpatterns = [
    path('', views.indexglav, name='indexglav'),
    path('news/<slug:slug>/', views.news_detail, name='news_detail'),
    path('liderplatform1/', views.liderplatform1, name='liderplatform1'),
    path('workshop1/', views.workshop1, name='workshop1'),
    path('documents1/', views.documents1, name='documents1'),
    path('shop1/', views.shop1, name='shop1'),
    path('service1/', views.service1, name='service1'),
    path('contact1/', views.contact1, name='contact1'),
    path('logout/', views.logout_view, name='logout'),
]

startpage/urls.py
from django.urls import path
from . import views

app_name = "startpage"
urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('vhod/', views.vhod, name='vhod'),
    path('liderplatform/', views.liderplatform, name='liderplatform'),
    path('workshop/', views.workshop, name='workshop'),
    path('documents/', views.documents, name='documents'),
    path('shop/', views.shop, name='shop'),
    path('service/', views.service, name='service'),
    path('contact/', views.contact, name='contact'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('cookie/', views.cookie, name='cookie'),
    path('soglasie/', views.soglasie, name='soglasie'),
]

indexglav/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import RegexValidator
from django.utils.text import slugify

User = get_user_model()

class Tag(models.Model):
    name = models.CharField('Название тега', max_length=50, unique=True)
    slug = models.SlugField('URL', unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

    def __str__(self):
        return self.name

class Newspost(models.Model):
    namepost = models.CharField('Название поста', max_length=100)
    humanpost = models.CharField('От кого новость', max_length=100)
    soderjanie = models.TextField('Содержание поста')
    postdate = models.DateTimeField('Дата и время поста', auto_now_add=True)
    post_photo = models.ImageField('Фото', upload_to='static/img', blank=True)
    slug = models.SlugField('URL', unique=True, blank=True)
    tags = models.ManyToManyField(Tag, verbose_name='Теги', related_name='news_posts')

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'
        ordering = ['-postdate']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.namepost)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.namepost

indexglav/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.db.models import Q
from .models import Newspost, Tag
from django.core.paginator import Paginator
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from comments.forms import CommentForm
from comments.models import Comment


def indexglav(request):
    tag_slug = request.GET.get('tag')
    search_query = request.GET.get('search', '')
    page = request.GET.get('page', 1)
    
    vivodnews = Newspost.objects.all()
    
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        vivodnews = vivodnews.filter(tags=tag)
        
    if search_query:
        vivodnews = vivodnews.filter(
            Q(namepost__icontains=search_query) |
            Q(soderjanie__icontains=search_query) |
            Q(humanpost__icontains=search_query)
        )
    
    # Пагинация: показываем максимум 10 новостей на странице
    paginator = Paginator(vivodnews, 10)
    page_obj = paginator.get_page(page)
    
    tags = Tag.objects.all()
    return render(request, 'indexglav.html', {
        'vivodnews': page_obj,
        'tags': tags,
        'current_tag': tag_slug,
        'search_query': search_query,
        'paginator': paginator,
        'page_obj': page_obj,
        'is_paginated': page_obj.has_other_pages()
    })

def news_detail(request, slug):
    """Отображение детальной страницы новости"""
    post = get_object_or_404(Newspost, slug=slug)
    tags = Tag.objects.all()
    
    # Get comments for this news post
    content_type = ContentType.objects.get_for_model(Newspost)
    comments = Comment.objects.filter(content_type=content_type, object_id=post.id)
    
    # Prepare comment form
    comment_form = CommentForm()
    comment_form_action = f'/comments/newspost/{post.id}/comment/'
    
    # Get related posts with the same tags
    related_posts = Newspost.objects.filter(tags__in=post.tags.all()).exclude(id=post.id).distinct()[:3]
    
    context = {
        'post': post,
        'tags': tags,
        'related_posts': related_posts,
        'comments': comments,
        'comment_form': comment_form,
        'comment_form_action': comment_form_action,
    }
    
    return render(request, 'news_detail.html', context)

def liderplatform1(request):
    return render(request, 'glavfooter/liderplatform.html')
    
def workshop1(request):
    return render(request, 'glavfooter/workshop.html')

def documents1(request):
    return render(request, 'glavfooter/documents.html')

def shop1(request):
    return render(request, 'glavfooter/shop.html')

def service1(request):
    return render(request, 'glavfooter/service.html')

def contact1(request):
    return render(request, 'glavfooter/contact.html')
    
def logout_view(request):
    logout(request)
    return redirect('startpage:home')

indexglav/templates/glavfooter/contact.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>InnoAuthor</title>
	<link href="https://fonts.googleapis.com/css?family=Oswald:300,400,500" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Roboto:300i,400,500" rel="stylesheet">

	<link rel="stylesheet" href="{% static 'vendor/themify-icons/themify-icons.css'%}">
	<link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
	<link rel="stylesheet" href="{% static 'vendor/owl-carousel/owl.theme.default.min.css'%}">
	<link rel="stylesheet" href="{% static 'vendor/owl-carousel/owl.carousel.min.css'%}">
	<link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.min.css'%}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>

	{% include 'includes/header.html' %}

	<br><br><br><br>

	<section class="section-margin">
		<div class="container">
			<div class="row align-items-center">
				<div class="col-md-4 col-lg-3 mb-4 mb-md-0">
					<div class="media contact-info">
						<span class="contact-info__icon"><i class="lnr lnr-home"></i></span>
						<div class="media-body">
							<h3>Москва Российская Федерация</h3>
							<p>Ул Авиамоторная 10</p>
						</div>
					</div>
					<div class="media contact-info">
						<span class="contact-info__icon"><i class="lnr lnr-phone-handset"></i></span>
						<div class="media-body">
							<h3><a href="tel:79771611006">+7 (977) 161 1006</a></h3>
							<p>Звоните с 9:00 до 18:00 по МСК</p>
						</div>
					</div>
					<div class="media contact-info">
						<span class="contact-info__icon"><i class="lnr lnr-envelope"></i></span>
						<div class="media-body">
							<h3><a href="mailto:shushpanov-official@yandex.ru">shushpanov-official@yandex.ru</a></h3>
							<p>Отправляйте запрос в любое время!</p>
						</div>
					</div>
				</div>
				<div class="col-md-8 col-lg-9">
					<form action="#/" class="form-contact">
						<div class="row">
							<div class="col-lg-5">
								<div class="form-group">
									<input class="form-control" name="name" type="text" placeholder="Логин" required>
								</div>
								<div class="form-group">
									<input class="form-control" name="email" type="email" placeholder="Ваша почта"
										required>
								</div>
								<div class="form-group">
									<input class="form-control" name="subject" type="text" placeholder="Тема обращения">
								</div>
							</div>
							<div class="col-lg-7">
								<div class="form-group">
									<textarea class="form-control different-control w-100" name="textarea" id="textarea"
										cols="30" rows="6" placeholder="Текст обращения"></textarea>
								</div>
							</div>
						</div>
						<div class="form-group text-center text-md-right">
							<button type="submit" class="btn active btn--leftBorder">Отправить сообщение</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</section>


	<footer class="footer footer-bg">
		<div class="container">
			<div class="row">
				<div class="col-sm-4 col-lg-2 mb-4 mb-lg-0 text-left">
					<h3 class="footer__title">Организация</h3>
					<ul class="footer__link">
						<li><a href="{% url 'indexglav:liderplatform1' %}">Структура платформы</a></li>
					</ul>
				</div>
				<div class="col-sm-4 col-lg-2 mb-4 mb-lg-0 text-left">
					<h3 class="footer__title">Полезные ссылки</h3>
					<ul class="footer__link">
						<li><a href="{% url 'indexglav:workshop1' %}">Вакансии</a></li>
						<li><a href="https://pay.cloudtips.ru/p/925045f4">Вклады</a></li>

					</ul>
				</div>
				<div class="col-sm-4 col-lg-2 mb-4 mb-lg-0 text-left">
					<h3 class="footer__title">Для пользователей</h3>
					<ul class="footer__link">
						<li><a href="{% url 'indexglav:documents1' %}">Документы</a></li>
						<li><a href="{% url 'indexglav:shop1' %}">Магазин</a></li>
						<li><a href="{% url 'indexglav:service1' %}">Услуги</a></li>
					</ul>
				</div>
				<div class="col-sm-4 col-lg-2 mb-4 mb-lg-0 text-left">
					<h3 class="footer__title">Информация</h3>
					<ul class="footer__link">
						<li><a href="{% url 'indexglav:contact1' %}">Связаться с нами</a></li>
					</ul>
				</div>
				
			</div>
			<div class="d-sm-flex justify-content-between footer__bottom top-border">
				<p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					InnoAuthor &copy;
					<script>document.write(new Date().getFullYear());</script> Все права защищены | Этот проект <i
						class="fa fa-heart" aria-hidden="true"></i> производства <a href="https://colorlib.com"
						target="_blank">shushpanov_official</a>
					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
				</p>
				<ul class="social-icons mt-2 mt-sm-0">

					<li><a href="https://t.me/sevendayswiththebureau" target="_blank"><i
								class='fab fa-telegram'></i></a></li>

					<li><a href="https://vk.com/7daywithburo" target="_blank"><i class='fab fa-vk'></i> </a></li>

					<li><a href="https://dzen.ru/sevendayswiththebureau" target="_blank"><i
								class='fab fa-yandex-international'></i> </a></li>
				</ul>
			</div>
		</div>
	</footer>



	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js'%}"></script>
	<script src="{% static 'vendor/bootstrap/bootstrap.bundle.min.js'%}"></script>
	<script src="{% static 'vendor/owl-carousel/owl.carousel.min.js'%}"></script>

	<script>
		var dropToggle = $('.menu_right > li').has('ul').children('a');
		dropToggle.on('click', function () {
			dropToggle.not(this).closest('li').find('ul').slideUp(200);
			$(this).closest('li').children('ul').slideToggle(200);
			return false;
		});

		$(".toggle_icon").on('click', function () {
			$('body').toggleClass("open");
		});
	</script>
</body>

</html>

indexglav/templates/glavfooter/documents.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>InnoAuthor</title>
	<link href="https://fonts.googleapis.com/css?family=Oswald:300,400,500" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Roboto:300i,400,500" rel="stylesheet">

	<link rel="stylesheet" href="{% static 'vendor/themify-icons/themify-icons.css'%}">
	<link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
	<link rel="stylesheet" href="{% static 'vendor/owl-carousel/owl.theme.default.min.css'%}">
	<link rel="stylesheet" href="{% static 'vendor/owl-carousel/owl.carousel.min.css'%}">
	<link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.min.css'%}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>

	{% include 'includes/header.html' %}


	<section class="section-margin">
		<div class="container">
			<h3>Скачайте все документы, которые вам интересны</h3>

			<a href="/static/documents/Политика конфиденциальности.docx" class="genric-btn primary" download="Политика конфиденциальности.docx">Политика конфиденциальности</a>
		
		<a href="/static/documents/Пользовательское соглашение.docx" class="genric-btn primary" download="Пользовательское соглашение.docx">Пользовательское соглашение</a>
		
		<a href="/static/documents/Согласие на обработку персональных данных.docx" class="genric-btn primary" download="Согласие на обработку персональных данных.docx">Согласие на обработку персональных данных</a>
		
		<br><br><br>
		
		<a href="/static/documents/Реквизиты владельца сайта.docx" class="genric-btn primary" download="Реквизиты владельца сайта.docx">Реквизиты владельца сайта</a>
		
		<a href="/static/documents/Политика обработки cookies.docx" class="genric-btn primary" download="Политика обработки cookies.docx">Политика обработки cookies</a>
		
		<a href="/static/documents/Согласие на получение рекламных рассылок.docx" class="genric-btn primary" download="Согласие на получение рекламных рассылок.docx">Согласие на получение рекламных рассылок</a>
		
		<br><br><br>
		
		<a href="/static/documents/грант.pptx" class="genric-btn primary" download="грант.pptx">Как получить свой первый грант</a>
		
		
		<br><br><br>
		</div>
	</section>


	<footer class="footer footer-bg">
			<div class="container">
				<div class="row">
					<div class="col-sm-4 col-lg-2 mb-4 mb-lg-0 text-left">
						<h3 class="footer__title">Организация</h3>
						<ul class="footer__link">
							<li><a href="{% url 'startpage:liderplatform' %}">Структура платформы</a></li>
						</ul>
					</div>
					<div class="col-sm-4 col-lg-2 mb-4 mb-lg-0 text-left">
						<h3 class="footer__title">Полезные ссылки</h3>
						<ul class="footer__link">
							<li><a href="{% url 'startpage:workshop' %}">Вакансии</a></li>
							<li><a href="https://pay.cloudtips.ru/p/925045f4">Вклады</a></li>

						</ul>
					</div>
					<div class="col-sm-4 col-lg-2 mb-4 mb-lg-0 text-left">
						<h3 class="footer__title">Для пользователей</h3>
						<ul class="footer__link">
							<li><a href="{% url 'startpage:documents' %}">Документы</a></li>
							<li><a href="{% url 'startpage:shop' %}">Магазин</a></li>
							<li><a href="{% url 'startpage:service' %}">Услуги</a></li>
						</ul>
					</div>
					<div class="col-sm-4 col-lg-2 mb-4 mb-lg-0 text-left">
						<h3 class="footer__title">Информация</h3>
						<ul class="footer__link">
							<li><a href="{% url 'startpage:contact' %}">Связаться с нами</a></li>
						</ul>
					</div>
					
				</div>
				<div class="d-sm-flex justify-content-between footer__bottom top-border">
					<p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						InnoAuthor &copy;
						<script>document.write(new Date().getFullYear());</script> Все права защищены | Этот проект <i
							class="fa fa-heart" aria-hidden="true"></i> производства <a href="https://t.me/shushpanov_official"
							target="_blank">shushpanov_official</a>
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					</p>
					<ul class="social-icons mt-2 mt-sm-0">

						<li><a href="https://t.me/innoauthor" target="_blank"><i
									class='fab fa-telegram'></i></a></li>

						<li><a href="https://vk.com/innoauthor" target="_blank"><i class='fab fa-vk'></i> </a></li>

					
					</ul>
				</div>
			</div>
		</footer>



	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js'%}"></script>
	<script src="{% static 'vendor/bootstrap/bootstrap.bundle.min.js'%}"></script>
	<script src="{% static 'vendor/owl-carousel/owl.carousel.min.js'%}"></script>

	<script>
		var dropToggle = $('.menu_right > li').has('ul').children('a');
		dropToggle.on('click', function () {
			dropToggle.not(this).closest('li').find('ul').slideUp(200);
			$(this).closest('li').children('ul').slideToggle(200);
			return false;
		});

		$(".toggle_icon").on('click', function () {
			$('body').toggleClass("open");
		});
	</script>
</body>

</html>

indexglav/templates/glavfooter/service.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>InnoAuthor</title>
	<link href="https://fonts.googleapis.com/css?family=Oswald:300,400,500" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Roboto:300i,400,500" rel="stylesheet">

	<link rel="stylesheet" href="{% static 'vendor/themify-icons/themify-icons.css'%}">
	<link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
	<link rel="stylesheet" href="{% static 'vendor/owl-carousel/owl.theme.default.min.css'%}">
	<link rel="stylesheet" href="{% static 'vendor/owl-carousel/owl.carousel.min.css'%}">
	<link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.min.css'%}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
	{% include 'includes/header.html' %}

	<section class="service section-margin mb-5 pb-5">
		<div class="container">
			<div class="section-intro">
				<h4 class="section-intro__title">Услуги</h4>
				<h2 class="section-intro__subtitle bottom-border">Наши услуги</h2>
			</div>

			<div class="row">
        <div class="col-sm-6 col-lg-4">
		<a href="{% url 'startpage:contact' %}">
          <div class="media service__single">
            <span class="service__singleIcon"><i class="ti-package"></i></span>
            <div class="media-body">
              <h3>Подготовка вашего проекта для инвестиций</h3>
              <p>Наш специалист проверит ваш проект и напишит рекомендации по улучшению проекта.<br><br>
			  
			  </p>
            </div>
          </div>
		  </a>
        </div>
        <div class="col-sm-6 col-lg-4">
		<a href="{% url 'startpage:contact' %}">
          <div class="media service__single">
            <span class="service__singleIcon"><i class="ti-home"></i></span>
            <div class="media-body">
              <h3>Помощь в получение гранта</h3>
              <p>Наш специалист подготовит вам грантовую заявку.<br><br>
			  
			  </p>
            </div>
          </div>
		  </a>
        </div>
        <div class="col-sm-6 col-lg-4">
		<a href="{% url 'startpage:contact' %}">
          <div class="media service__single">
            <span class="service__singleIcon"><i class="ti-brush-alt"></i></span>
            <div class="media-body">
              <h3>Юридическая консультация вашего проекта</h3>
              <p>Наш специалист проверит ваш проект и напишит рекомендации по защите проекта.<br><br>
			  </p>
            </div>
          </div>
		  </a>
        </div>
        <div class="col-sm-6 col-lg-4">
		<a href="{% url 'startpage:contact' %}">
          <div class="media service__single">
            <span class="service__singleIcon"><i class="ti-package"></i></span>
            <div class="media-body">
              <h3>Продвижение вашего проекта</h3>
              <p>Мы можем опубликовать ваш проект в новостной ленте, продвинуть его в списке проектов, присвоить статус "Перспективный проект" (При условии проверки специалиста), 
			  мы также сотрудничаем с рядом блогеров.<br><br>
			  
			  </p>
            </div>
          </div>
		  </a>
        </div>
        <div class="col-sm-6 col-lg-4">
		<a href="{% url 'startpage:contact' %}">
          <div class="media service__single">
            <span class="service__singleIcon"><i class="ti-home"></i></span>
            <div class="media-body">
              <h3>Подготовка сайта проекта</h3>
              <p>Подготовим сайт по готовым кейсам нашей компании.<br><br>
				
			  </p>
			  
            </div>
          </div>
		  </a>
        </div>
		
        <div class="col-sm-6 col-lg-4">
		<a href="{% url 'startpage:contact' %}">
          <div class="media service__single">
            <span class="service__singleIcon"><i class="ti-brush-alt"></i></span>
            <div class="media-body">
              <h3>Пригласительные на бизнес встречи </h3>
              <p>Мы организовываем совместно с нашими партнерами закрытые бизнес форумы.<br><br>
				
			  </p>
            </div>
          </div>
		  </a>
        </div>
		
			</div>
		</div>
  </section>



	<footer class="footer footer-bg">
		<div class="container">
			<div class="row">
				<div class="col-sm-4 col-lg-2 mb-4 mb-lg-0 text-left">
					<h3 class="footer__title">Организация</h3>
					<ul class="footer__link">
						<li><a href="{% url 'indexglav:liderplatform1' %}">Структура платформы</a></li>
					</ul>
				</div>
				<div class="col-sm-4 col-lg-2 mb-4 mb-lg-0 text-left">
					<h3 class="footer__title">Полезные ссылки</h3>
					<ul class="footer__link">
						<li><a href="{% url 'indexglav:workshop1' %}">Вакансии</a></li>
						<li><a href="https://pay.cloudtips.ru/p/925045f4">Вклады</a></li>

					</ul>
				</div>
				<div class="col-sm-4 col-lg-2 mb-4 mb-lg-0 text-left">
					<h3 class="footer__title">Для пользователей</h3>
					<ul class="footer__link">
						<li><a href="{% url 'indexglav:documents1' %}">Документы</a></li>
						<li><a href="{% url 'indexglav:shop1' %}">Магазин</a></li>
						<li><a href="{% url 'indexglav:service1' %}">Услуги</a></li>
					</ul>
				</div>
				<div class="col-sm-4 col-lg-2 mb-4 mb-lg-0 text-left">
					<h3 class="footer__title">Информация</h3>
					<ul class="footer__link">
						<li><a href="{% url 'indexglav:contact1' %}">Связаться с нами</a></li>
					</ul>
				</div>
				
			</div>
			<div class="d-sm-flex justify-content-between footer__bottom top-border">
				<p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					InnoAuthor &copy;
					<script>document.write(new Date().getFullYear());</script> Все права защищены | Этот проект <i
						class="fa fa-heart" aria-hidden="true"></i> производства <a href="https://colorlib.com"
						target="_blank">shushpanov_official</a>
					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
				</p>
				<ul class="social-icons mt-2 mt-sm-0">

					<li><a href="https://t.me/sevendayswiththebureau" target="_blank"><i
								class='fab fa-telegram'></i></a></li>

					<li><a href="https://vk.com/7daywithburo" target="_blank"><i class='fab fa-vk'></i> </a></li>

					<li><a href="https://dzen.ru/sevendayswiththebureau" target="_blank"><i
								class='fab fa-yandex-international'></i> </a></li>
				</ul>
			</div>
		</div>
	</footer>



	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js'%}"></script>
	<script src="{% static 'vendor/bootstrap/bootstrap.bundle.min.js'%}"></script>
	<script src="{% static 'vendor/owl-carousel/owl.carousel.min.js'%}"></script>

	<script>
		var dropToggle = $('.menu_right > li').has('ul').children('a');
		dropToggle.on('click', function () {
			dropToggle.not(this).closest('li').find('ul').slideUp(200);
			$(this).closest('li').children('ul').slideToggle(200);
			return false;
		});

		$(".toggle_icon").on('click', function () {
			$('body').toggleClass("open");
		});
	</script>
</body>

</html>