InnAuthor/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views

from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace="users")),
    path('', include('startpage.urls', namespace="startpage")),
    path('news/', include('indexglav.urls', namespace="indexglav")),
    path('projects/', include('projects.urls', namespace="projects")),
    path('about/', include('about.urls', namespace="about")),
    path('exite/', include('exite.urls', namespace="exite")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('comments/', include('comments.urls', namespace="comments")),
    
    # Password reset URLs
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), 
        name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), 
        name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), 
        name='password_reset_complete'),
]

# Добавляем поддержку статических файлов в режиме отладки
urlpatterns += staticfiles_urlpatterns()

# Добавляем обработку медиа файлов в режиме отладки
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

about/urls.py
from django.urls import path
from . import views

app_name = "about"
urlpatterns = [
    path('', views.about, name='about'),
    path('liderplatform1/', views.liderplatform1, name='liderplatform1'),
    path('workshop1/', views.workshop1, name='workshop1'),
    path('documents1/', views.documents1, name='documents1'),
    path('shop1/', views.shop1, name='shop1'),
    path('service1/', views.service1, name='service1'),
    path('contact1/', views.contact1, name='contact1'),
]

indexglav/urls.py
from django.urls import path
from . import views

app_name = "indexglav"
urlpatterns = [
    path('', views.indexglav, name='indexglav'),
    path('news/<slug:slug>/', views.news_detail, name='news_detail'),
    path('liderplatform1/', views.liderplatform1, name='liderplatform1'),
    path('workshop1/', views.workshop1, name='workshop1'),
    path('documents1/', views.documents1, name='documents1'),
    path('shop1/', views.shop1, name='shop1'),
    path('service1/', views.service1, name='service1'),
    path('contact1/', views.contact1, name='contact1'),
    path('logout/', views.logout_view, name='logout'),
]

startpage/urls.py
from django.urls import path
from . import views

app_name = "startpage"
urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('vhod/', views.vhod, name='vhod'),
    path('liderplatform/', views.liderplatform, name='liderplatform'),
    path('workshop/', views.workshop, name='workshop'),
    path('documents/', views.documents, name='documents'),
    path('shop/', views.shop, name='shop'),
    path('service/', views.service, name='service'),
    path('contact/', views.contact, name='contact'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('cookie/', views.cookie, name='cookie'),
    path('soglasie/', views.soglasie, name='soglasie'),
]

users/urls.py
from django.urls import path
from . import views


app_name = "users"
urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('verify/<str:token>/', views.verify_email, name='verify_email'),
    path('profile/', views.profile, name='profile'),
    path('profile/general/', views.profile_general, name='profile_general'),
    path('profile/security/', views.profile_security, name='profile_security'),
    path('user/<str:username>/', views.public_profile, name='public_profile'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}InnoAuthor{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Oswald:300,400,500" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300i,400,500" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'vendor/themify-icons/themify-icons.css'%}">
    <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <link rel="stylesheet" href="{% static 'vendor/owl-carousel/owl.theme.default.min.css'%}">
    <link rel="stylesheet" href="{% static 'vendor/owl-carousel/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/fix-header.css' %}">
    {% block extra_css %}{% endblock %}
</head>

<body>
    {% include 'includes/header.html' %}

    <!-- Main Content -->
    {% block content %}{% endblock %}

    <!-- Footer -->
    <footer class="footer footer-bg">
			<div class="container">
				<div class="row">
					<div class="col-sm-4 col-lg-2 mb-4 mb-lg-0 text-left">
						<h3 class="footer__title">Организация</h3>
						<ul class="footer__link">
							<li><a href="{% url 'startpage:liderplatform' %}">Структура платформы</a></li>
						</ul>
					</div>
					<div class="col-sm-4 col-lg-2 mb-4 mb-lg-0 text-left">
						<h3 class="footer__title">Полезные ссылки</h3>
						<ul class="footer__link">
							<li><a href="{% url 'startpage:workshop' %}">Вакансии</a></li>
							<li><a href="https://pay.cloudtips.ru/p/925045f4">Вклады</a></li>

						</ul>
					</div>
					<div class="col-sm-4 col-lg-2 mb-4 mb-lg-0 text-left">
						<h3 class="footer__title">Для пользователей</h3>
						<ul class="footer__link">
							<li><a href="{% url 'startpage:documents' %}">Документы</a></li>
							<li><a href="{% url 'startpage:shop' %}">Магазин</a></li>
							<li><a href="{% url 'startpage:service' %}">Услуги</a></li>
						</ul>
					</div>
					<div class="col-sm-4 col-lg-2 mb-4 mb-lg-0 text-left">
						<h3 class="footer__title">Информация</h3>
						<ul class="footer__link">
							<li><a href="{% url 'startpage:contact' %}">Связаться с нами</a></li>
						</ul>
					</div>
					
				</div>
				<div class="d-sm-flex justify-content-between footer__bottom top-border">
					<p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						InnoAuthor &copy;
						<script>document.write(new Date().getFullYear());</script> Все права защищены | Этот проект <i
							class="fa fa-heart" aria-hidden="true"></i> производства <a href="https://t.me/shushpanov_official"
							target="_blank">shushpanov_official</a>
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					</p>
					<ul class="social-icons mt-2 mt-sm-0">

						<li><a href="https://t.me/innoauthor" target="_blank"><i
									class='fab fa-telegram'></i></a></li>

						<li><a href="https://vk.com/innoauthor" target="_blank"><i class='fab fa-vk'></i> </a></li>

					
					</ul>
				</div>
			</div>
		</footer>

    <!-- Scripts -->
    <script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/owl-carousel/owl.carousel.min.js' %}"></script>
    <script>
        var dropToggle = $('.menu_right > li').has('ul').children('a');
        dropToggle.on('click', function () {
            dropToggle.not(this).closest('li').find('ul').slideUp(200);
            $(this).closest('li').children('ul').slideToggle(200);
            return false;
        });

        $(".toggle_icon").on('click', function () {
            $('body').toggleClass("open");
        });
    </script>
    {% block extra_js %}{% endblock %}
</body>

</html>

templates/documents.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>InnoAuthor</title>
	<link href="https://fonts.googleapis.com/css?family=Oswald:300,400,500" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Roboto:300i,400,500" rel="stylesheet">

	<link rel="stylesheet" href="{% static 'vendor/themify-icons/themify-icons.css'%}">
	<link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
	<link rel="stylesheet" href="{% static 'vendor/owl-carousel/owl.theme.default.min.css'%}">
	<link rel="stylesheet" href="{% static 'vendor/owl-carousel/owl.carousel.min.css'%}">
	<link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.min.css'%}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/fix-header.css' %}">
</head>
<body>

		<!-- ================Offcanvus Menu Area =================-->
	{% include 'includes/header.html' %}
	<!--================End Offcanvus Menu Area =================-->


  <section class="section-margin">
    <div class="container">
	<h3>Скачайте все документы, которые вам интересны</h3>
      
		<a href="/static/documents/Политика конфиденциальности.docx" class="genric-btn primary" download="Политика конфиденциальности.docx">Политика конфиденциальности</a>
		
		<a href="/static/documents/Пользовательское соглашение.docx" class="genric-btn primary" download="Пользовательское соглашение.docx">Пользовательское соглашение</a>
		
		<a href="/static/documents/Согласие на обработку персональных данных.docx" class="genric-btn primary" download="Согласие на обработку персональных данных.docx">Согласие на обработку персональных данных</a>
		
		<br><br><br>
		
		<a href="/static/documents/Реквизиты владельца сайта.docx" class="genric-btn primary" download="Реквизиты владельца сайта.docx">Реквизиты владельца сайта</a>
		
		<a href="/static/documents/Политика обработки cookies.docx" class="genric-btn primary" download="Политика обработки cookies.docx">Политика обработки cookies</a>
		
		<a href="/static/documents/Согласие на получение рекламных рассылок.docx" class="genric-btn primary" download="Согласие на получение рекламных рассылок.docx">Согласие на получение рекламных рассылок</a>
		
		<br><br><br>
		
		<a href="/static/documents/грант.pptx" class="genric-btn primary" download="грант.pptx">Как получить свой первый грант</a>
		
		
		<br><br><br>
      
    </div>
  </section>
  

<footer class="footer footer-bg">
			<div class="container">
				<div class="row">
					<div class="col-sm-4 col-lg-2 mb-4 mb-lg-0 text-left">
						<h3 class="footer__title">Организация</h3>
						<ul class="footer__link">
							<li><a href="{% url 'startpage:liderplatform' %}">Структура платформы</a></li>
						</ul>
					</div>
					<div class="col-sm-4 col-lg-2 mb-4 mb-lg-0 text-left">
						<h3 class="footer__title">Полезные ссылки</h3>
						<ul class="footer__link">
							<li><a href="{% url 'startpage:workshop' %}">Вакансии</a></li>
							<li><a href="https://pay.cloudtips.ru/p/925045f4">Вклады</a></li>

						</ul>
					</div>
					<div class="col-sm-4 col-lg-2 mb-4 mb-lg-0 text-left">
						<h3 class="footer__title">Для пользователей</h3>
						<ul class="footer__link">
							<li><a href="{% url 'startpage:documents' %}">Документы</a></li>
							<li><a href="{% url 'startpage:shop' %}">Магазин</a></li>
							<li><a href="{% url 'startpage:service' %}">Услуги</a></li>
						</ul>
					</div>
					<div class="col-sm-4 col-lg-2 mb-4 mb-lg-0 text-left">
						<h3 class="footer__title">Информация</h3>
						<ul class="footer__link">
							<li><a href="{% url 'startpage:contact' %}">Связаться с нами</a></li>
						</ul>
					</div>
					
				</div>
				<div class="d-sm-flex justify-content-between footer__bottom top-border">
					<p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						InnoAuthor &copy;
						<script>document.write(new Date().getFullYear());</script> Все права защищены | Этот проект <i
							class="fa fa-heart" aria-hidden="true"></i> производства <a href="https://t.me/shushpanov_official"
							target="_blank">shushpanov_official</a>
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					</p>
					<ul class="social-icons mt-2 mt-sm-0">

						<li><a href="https://t.me/innoauthor" target="_blank"><i
									class='fab fa-telegram'></i></a></li>

						<li><a href="https://vk.com/innoauthor" target="_blank"><i class='fab fa-vk'></i> </a></li>

					
					</ul>
				</div>
			</div>
		</footer>



	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js'%}"></script>	
	<script src="{% static 'vendor/bootstrap/bootstrap.bundle.min.js'%}"></script>
	<script src="{% static 'vendor/owl-carousel/owl.carousel.min.js'%}"></script>
  
  <script>
    var dropToggle = $('.menu_right > li').has('ul').children('a');
        dropToggle.on('click', function() {
          dropToggle.not(this).closest('li').find('ul').slideUp(200);
          $(this).closest('li').children('ul').slideToggle(200);
          return false;
        });

        $( ".toggle_icon" ).on('click', function() {
          $( 'body' ).toggleClass( "open" );
        });
  </script>
</body>
</html>

templates/liderplatform.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>InnoAuthor</title>
	<link href="https://fonts.googleapis.com/css?family=Oswald:300,400,500" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Roboto:300i,400,500" rel="stylesheet">

	<link rel="stylesheet" href="{% static 'vendor/themify-icons/themify-icons.css'%}">
	<link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
	<link rel="stylesheet" href="{% static 'vendor/owl-carousel/owl.theme.default.min.css'%}">
	<link rel="stylesheet" href="{% static 'vendor/owl-carousel/owl.carousel.min.css'%}">
	<link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.min.css'%}">
  	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="{% static 'css/fix-header.css' %}">
</head>
<body>

	{% include 'includes/header.html' %}

  	<section class="about section-margin mb-5">
		<div class="container">
			<div class="row align-items-center">
				<div class="col-md-5">
					<div class="about__img text-center text-md-left mb-5 mb-md-0">
						<img class="img-fluid" src="img/Shushpanov_Live.png" alt="">
						<a href="#/" class="about__img__date text-center">
							<h3>6 лет создаем проекты будущего</h3>
						</a>
					</div>
				</div>
				<div class="col-md-7 pl-xl-5">
					<div class="section-intro">
						<h4 class="section-intro__title">Про нашу команду</h4>
						<h2 class="section-intro__subtitle">Наша команда была <br> создана в 2019</h2>
					</div>
					<p>Команда разработчиков платформы InnoAuthor — это наша команда новаторов, превращающих инновационные идеи в
					реальные проекты и создающих уникальную экосистему для реализации инноваций. Мы не просто создаём технологические решения,
					а формируем пространство, где каждый может воплотить свои прорывные задумки, используя современные инструменты и процессы.

Наша команда обладает глубоким техническим опытом, что позволяет создавать надёжные, масштабируемые и удобные платформы. 
Наша работа направлена на облегчение пути для инноваторов, 
обеспечивая поддержку от идеи до её воплощения.

InnoAuthor — это больше, чем просто платформа. Это мощный инструмент для вдохновения, поддержки и развития инновационных проектов, где
 технологии и креативность идут рука об руку. Мы помогаем каждому пользователю раскрыть потенциал своих идей, превращая их в реальные
 технологии и решения, которые могут изменить рынок и общество.

Наша миссия — ускорять научно-технический прогресс и создавать условия для внедрения инноваций, поддерживая разработчиков и стартапы на 
всех этапах пути. Такой подход делает нас настоящими лидерами в сфере инновационных платформ и примером того, как инновации могут быть
 реализованы эффективно и с душой.

Наша команда — движущая сила прогресса, создающая будущее, где инновации становятся доступными и понятными каждому, кто хочет менять
 мир! Продолжайте вдохновлять и создавать вместе с нами!</p>
					
			</div>
		</div>
	</section>
	



	

	

	<section class="testimonial section-margin">
		<div class="container">
			<div class="section-intro">
				<h4 class="section-intro__title">Раздел</h4>
				<h2 class="section-intro__subtitle bottom-border">Благодарность</h2>
			</div>
			<h4 class="section-intro__title">Шушпанов Михаил </h4>
			<h4 class="section-intro__title">Максимова Яна</h4>
			<h4 class="section-intro__title">Саражинский Никита </h4> 
			<h4 class="section-intro__title">Макаров Андрей</h4>
			<h4 class="section-intro__title">Коновалов Николай</h4>
			<h4 class="section-intro__title">Лысенкова Ирина</h4>
			<h4 class="section-intro__title">Пехов Александр</h4>
			<h4 class="section-intro__title">Сергеев Сергей</h4>
			<h4 class="section-intro__title">Запышнюк Анастасия</h4>
			<h4 class="section-intro__title">Ерин Денис</h4>
			<h4 class="section-intro__title">Челла Андрей</h4>

			<br>
		</div>
	</section>


				<div class="progress-table-wrap">
					<div class="progress-table">
					<h3>Страны в которых мы работаем:</h3>
						<div class="table-head">
							<div class="serial">#</div>
							<div class="country">Countries</div>
							
							<div class="visit">Visits</div>
							<div class="percentage">Percentages</div>
						</div>
						<div class="table-row">
							<div class="serial">01</div>
							<div class="country"> Russia</div>
							<div class="visit">30</div>
							<div class="percentage">
								<div class="progress">
								
									<div class="progress-bar color-1" role="progressbar" style="width: 80%" aria-valuenow="50" aria-valuemin="80" aria-valuemax="50"></div>
								</div>
							</div>
						</div>
						
					</div>
				</div>

  

	<footer class="footer footer-bg">
			<div class="container">
				<div class="row">
					<div class="col-sm-4 col-lg-2 mb-4 mb-lg-0 text-left">
						<h3 class="footer__title">Организация</h3>
						<ul class="footer__link">
							<li><a href="{% url 'startpage:liderplatform' %}">Структура платформы</a></li>
						</ul>
					</div>
					<div class="col-sm-4 col-lg-2 mb-4 mb-lg-0 text-left">
						<h3 class="footer__title">Полезные ссылки</h3>
						<ul class="footer__link">
							<li><a href="{% url 'startpage:workshop' %}">Вакансии</a></li>
							<li><a href="https://pay.cloudtips.ru/p/925045f4">Вклады</a></li>

						</ul>
					</div>
					<div class="col-sm-4 col-lg-2 mb-4 mb-lg-0 text-left">
						<h3 class="footer__title">Для пользователей</h3>
						<ul class="footer__link">
							<li><a href="{% url 'startpage:documents' %}">Документы</a></li>
							<li><a href="{% url 'startpage:shop' %}">Магазин</a></li>
							<li><a href="{% url 'startpage:service' %}">Услуги</a></li>
						</ul>
					</div>
					<div class="col-sm-4 col-lg-2 mb-4 mb-lg-0 text-left">
						<h3 class="footer__title">Информация</h3>
						<ul class="footer__link">
							<li><a href="{% url 'startpage:contact' %}">Связаться с нами</a></li>
						</ul>
					</div>
					
				</div>
				<div class="d-sm-flex justify-content-between footer__bottom top-border">
					<p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						InnoAuthor &copy;
						<script>document.write(new Date().getFullYear());</script> Все права защищены | Этот проект <i
							class="fa fa-heart" aria-hidden="true"></i> производства <a href="https://t.me/shushpanov_official"
							target="_blank">shushpanov_official</a>
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					</p>
					<ul class="social-icons mt-2 mt-sm-0">

						<li><a href="https://t.me/innoauthor" target="_blank"><i
									class='fab fa-telegram'></i></a></li>

						<li><a href="https://vk.com/innoauthor" target="_blank"><i class='fab fa-vk'></i> </a></li>

					
					</ul>
				</div>
			</div>
		</footer>


	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js'%}"></script>	
	<script src="{% static 'vendor/bootstrap/bootstrap.bundle.min.js'%}"></script>
	<script src="{% static 'vendor/owl-carousel/owl.carousel.min.js'%}"></script>

	<script>
		var testimonialCarousel = $('.testimonialCarousel');
      testimonialCarousel.owlCarousel({
      loop:true,
      margin:80,
      startPosition: 2,
      nav: false,
      responsiveClass:true,
      responsive:{
        0:{
            items:1
        },
        1000:{
            items:2,
            loop:true
        }
      }
    });

    var heroCarousel = $('.heroCarousel');
      heroCarousel.owlCarousel({
      loop:true,
      margin:10,
      nav: false,
      startPosition: 1,
      responsiveClass:true,
      responsive:{
        0:{
            items:1
        }
      }
	});

	var dropToggle = $('.menu_right > li').has('ul').children('a');
	dropToggle.on('click', function() {
		dropToggle.not(this).closest('li').find('ul').slideUp(200);
		$(this).closest('li').children('ul').slideToggle(200);
		return false;
	});

	$( ".toggle_icon" ).on('click', function() {
		$( 'body' ).toggleClass( "open" );
	});

	</script>
</body>
</html>

templates/password_reset_complete.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Пароль изменен - InnoAuthor</title>
    <link href="https://fonts.googleapis.com/css?family=Oswald:300,400,500" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300i,400,500" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'vendor/themify-icons/themify-icons.css'%}">
    <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <link rel="stylesheet" href="{% static 'vendor/owl-carousel/owl.theme.default.min.css'%}">
    <link rel="stylesheet" href="{% static 'vendor/owl-carousel/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>
        .login-link {
            margin-top: 15px;
            display: block;
            text-align: center;
            color: #007bff;
            transition: all 0.3s;
            font-weight: 500;
            font-size: 16px;
        }

        .message-box {
            background-color: #d4edda;
            border-color: #c3e6cb;
            color: #155724;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
        }

        .btn-login {
            background: #007bff;
            color: white;
            border: none;
            padding: 12px 30px;
            margin-top: 10px;
            border-radius: 5px;
            font-weight: 500;
            letter-spacing: 0.5px;
            transition: all 0.3s;
            cursor: pointer;
            width: 100%;
            display: block;
            text-align: center;
            text-decoration: none;
        }

        .btn-login:hover {
            background: #0069d9;
            text-decoration: none;
            color: white;
        }
    </style>
</head>

<body>
    <!-- Start post-content Area -->
    <section class="post-content-area single-post-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 posts-list">
                    <div class="comment-form">
                        <h4 class="mb-4">Пароль успешно изменен</h4>

                        <div class="message-box">
                            <i class="fas fa-check-circle mr-2"></i>
                            <p>Ваш пароль был успешно изменен! Теперь вы можете войти в систему с новым паролем.</p>
                        </div>

                        <div class="form-group">
                            <a href="{% url 'users:login' %}" class="btn-login">Войти в систему</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 sidebar-widgets">
                    <div class="widget-wrap">
                        <div class="single-sidebar-widget user-info-widget">
                            <img src="{% static 'img/logo.png'%}" alt="">
                            <a href="#">
                                <h4>InnoAuthor</h4>
                            </a>
                            <p>
                                Платформа для реализации инновационных проектов
                            </p>
                            <ul class="social-links">
                                <li><a href="https://t.me/sevendayswiththebureau" target="_blank"><i
                                            class='fab fa-telegram'></i></a></li>
                                <li><a href="https://vk.com/7daywithburo" target="_blank"><i class='fab fa-vk'></i> </a>
                                </li>
                                <li><a href="https://dzen.ru/sevendayswiththebureau" target="_blank"><i
                                            class='fab fa-yandex-international'></i> </a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End post-content Area -->

    <script src="{% static 'vendor/jquery/jquery-3.2.1.min.js'%}"></script>
    <script src="{% static 'vendor/bootstrap/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'vendor/owl-carousel/owl.carousel.min.js'%}"></script>
</body>

</html>